package com.atguigu.mybatis.pojo;

public class Bangumi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.id
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.name
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.type
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.time
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.status
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.year
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.picture
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bangumi.userId
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.id
     *
     * @return the value of bangumi.id
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.id
     *
     * @param id the value for bangumi.id
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.name
     *
     * @return the value of bangumi.name
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.name
     *
     * @param name the value for bangumi.name
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.type
     *
     * @return the value of bangumi.type
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.type
     *
     * @param type the value for bangumi.type
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.time
     *
     * @return the value of bangumi.time
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.time
     *
     * @param time the value for bangumi.time
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.status
     *
     * @return the value of bangumi.status
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.status
     *
     * @param status the value for bangumi.status
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.year
     *
     * @return the value of bangumi.year
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.year
     *
     * @param year the value for bangumi.year
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.picture
     *
     * @return the value of bangumi.picture
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.picture
     *
     * @param picture the value for bangumi.picture
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bangumi.userId
     *
     * @return the value of bangumi.userId
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bangumi.userId
     *
     * @param userid the value for bangumi.userId
     *
     * @mbggenerated Thu Jan 05 17:43:52 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        return "Bangumi{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", type=" + type +
                ", time=" + time +
                ", status=" + status +
                ", year=" + year +
                ", picture='" + picture + '\'' +
                ", userid=" + userid +
                '}';
    }
}